# -*- coding: utf-8 -*-
"""resnet_with_ada_act.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bXU0_UOOsKq3uIZ0UJRdxD3r_vSwLMpq
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms

# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

class AdaAct(nn.Module):
    def __init__(self, activation_functions, initial_weights=None, bias=True):
        """
        Initialize the WeightedSumActivation module with learnable weights and bias.

        Parameters:
        - activation_functions: A list of PyTorch activation function objects (e.g., nn.ReLU()).
        - initial_weights: Optional initial values for weights (list of floats). If None, weights are initialized uniformly.
        - bias: If True, includes a learnable bias term.
        """
        super(AdaAct, self).__init__()

        self.activation_functions = nn.ModuleList(activation_functions)
        num_functions = len(activation_functions)

        # Initialize learnable weights
        if initial_weights is None:
            initial_weights = [1.0 / num_functions] * num_functions  # Uniform initialization
        self.weights = nn.Parameter(torch.tensor(initial_weights, dtype=torch.float32))

        # Initialize learnable bias
        if bias:
            self.bias = nn.Parameter(torch.tensor(0.0, dtype=torch.float32))
        else:
            self.bias = None

    def forward(self, x):
        """
        Forward pass for the weighted sum of activation functions with bias.

        Parameters:
        - x: The input tensor.

        Returns:
        - A tensor representing the weighted sum of activation functions applied to x, plus the bias.
        """
        output = torch.zeros_like(x)
        for activation, weight in zip(self.activation_functions, self.weights):
            output += weight * activation(x)

        if self.bias is not None:
            output += self.bias
        return output

import torch.nn as nn

all_acts = [
    nn.ReLU(),
    nn.LeakyReLU(),
    nn.PReLU(),
    nn.ELU(),
    nn.SELU(),
    nn.GELU(),
    nn.Tanh(),
    nn.Sigmoid(),
    nn.Softplus(),
    nn.Softsign(),
    nn.SiLU(),
    nn.Hardswish(),
    nn.Hardtanh(),
    nn.Hardsigmoid(),
    nn.LogSigmoid(),
    nn.Threshold(0.5, 0.0),
    nn.Softmax(dim=-1),
    nn.LogSoftmax(dim=-1)
]

# Basic Block for ResNet
class BasicBlock(nn.Module):
    expansion = 1

    def __init__(self, in_channels, out_channels, stride=1, downsample=None):
        super(BasicBlock, self).__init__()
        self.conv1 = nn.Conv2d(in_channels, out_channels, kernel_size=3, stride=stride, padding=1, bias=False)
        self.bn1 = nn.BatchNorm2d(out_channels)

        self.adaact1 = AdaAct(all_acts)

        self.conv2 = nn.Conv2d(out_channels, out_channels, kernel_size=3, stride=1, padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(out_channels)
        self.adaact2 = AdaAct(all_acts)
        self.downsample = downsample

    def forward(self, x):
        identity = x
        if self.downsample is not None:
            identity = self.downsample(x)

        out = self.conv1(x)
        out = self.bn1(out)
        out = self.adaact1(out)

        out = self.conv2(out)
        out = self.bn2(out)

        out += identity
        out = self.adaact2(out)

        return out

# ResNet-18 Model
class ResNet(nn.Module):
    def __init__(self, block, layers, num_classes=10):
        super(ResNet, self).__init__()
        self.in_channels = 64

        self.conv1 = nn.Conv2d(3, 64, kernel_size=7, stride=2, padding=3, bias=False)
        self.bn1 = nn.BatchNorm2d(64)

        self.adaact1 = AdaAct(all_acts)

        self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)

        self.layer1 = self._make_layer(block, 64, layers[0])
        self.layer2 = self._make_layer(block, 128, layers[1], stride=2)
        self.layer3 = self._make_layer(block, 256, layers[2], stride=2)
        self.layer4 = self._make_layer(block, 512, layers[3], stride=2)

        self.avgpool = nn.AdaptiveAvgPool2d((1, 1))
        self.fc = nn.Linear(512 * block.expansion, num_classes)

    def _make_layer(self, block, out_channels, blocks, stride=1):
        downsample = None
        if stride != 1 or self.in_channels != out_channels * block.expansion:
            downsample = nn.Sequential(
                nn.Conv2d(self.in_channels, out_channels * block.expansion, kernel_size=1, stride=stride, bias=False),
                nn.BatchNorm2d(out_channels * block.expansion),
            )

        layers = []
        layers.append(block(self.in_channels, out_channels, stride, downsample))
        self.in_channels = out_channels * block.expansion
        for _ in range(1, blocks):
            layers.append(block(self.in_channels, out_channels))

        return nn.Sequential(*layers)

    def forward(self, x):
        x = self.conv1(x)
        x = self.bn1(x)

        x = self.adaact1(x)
        x = self.maxpool(x)

        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)

        x = self.avgpool(x)
        x = torch.flatten(x, 1)
        x = self.fc(x)

        return x

# CIFAR-10 Dataset and DataLoader
transform = transforms.Compose([
    transforms.RandomHorizontalFlip(),
    transforms.RandomCrop(32, padding=4),
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])

train_dataset = datasets.CIFAR100(root='./data', train=True, download=True, transform=transform)
test_dataset = datasets.CIFAR100(root='./data', train=False, download=True, transform=transform)

train_loader = torch.utils.data.DataLoader(dataset=train_dataset, batch_size=128, shuffle=True)
test_loader = torch.utils.data.DataLoader(dataset=test_dataset, batch_size=128, shuffle=False)

# Define ResNet-18
def ResNet18AdaAct():
    return ResNet(BasicBlock, [2, 2, 2, 2])

model = ResNet18AdaAct().to(device)

model.to(device)

# Loss and Optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training Loop
num_epochs = 100

for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0
    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        # Forward pass
        outputs = model(images)
        loss = criterion(outputs, labels)

        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    train_accuracy = 100 * correct / total

    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {running_loss/len(train_loader):.4f}, Train accuracy : {train_accuracy:.2f}") #-----------------print accuracy

model.eval()
correct = 0
total = 0

with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

accuracy = 100 * correct / total

print(f"Test Accuracy: {accuracy:.2f}%")

